-- Create blogs table
create table if not exists blogs (
  id bigint generated by default as identity primary key,
  title_en text not null,
  title_ar text not null,
  excerpt_en text,
  excerpt_ar text,
  content_en text,
  content_ar text,
  author_en text,
  author_ar text,
  category text,
  image text,
  featured boolean default false,
  views int default 0,
  comments_count int default 0,
  read_time_en text,
  read_time_ar text,
  tags_en text[],
  tags_ar text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table blogs enable row level security;

-- Policies
create policy "Public blogs are viewable by everyone"
  on blogs for select
  using (true);

create policy "Admins can insert blogs"
  on blogs for insert
  with check (auth.role() = 'authenticated'); -- Or specific admin check if configured

create policy "Admins can update blogs"
  on blogs for update
  using (auth.role() = 'authenticated');

create policy "Admins can delete blogs"
  on blogs for delete
  using (auth.role() = 'authenticated');
