-- Create contact_messages table
create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table contact_messages enable row level security;

-- Policies
create policy "Anyone can insert messages"
  on contact_messages for insert
  with check (true);

create policy "Admins can view messages"
  on contact_messages for select
  using (auth.role() = 'authenticated');

create policy "Admins can update messages"
  on contact_messages for update
  using (auth.role() = 'authenticated');

create policy "Admins can delete messages"
  on contact_messages for delete
  using (auth.role() = 'authenticated');
