-- Create subscribers table
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'active'
);

-- Enable RLS
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;

-- Allow insert from public (anyone can subscribe)
CREATE POLICY "Enable insert for all users" ON subscribers FOR INSERT WITH CHECK (true);

-- Allow select only for admins (we'll use service role key in API anyway, but good for Supabase Studio)
-- (Assuming auth logic, but for simplicity we rely on service role in API)
