-- Create testimonials table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'Customer', -- e.g. Parent, Student, Teacher
  content TEXT,
  image TEXT, -- URL to avatar or screenshot
  rating INTEGER DEFAULT 5,
  source TEXT DEFAULT 'website', -- website, facebook, google
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public can view approved testimonials" ON testimonials FOR SELECT USING (is_approved = true);
CREATE POLICY "Public can insert testimonials" ON testimonials FOR INSERT WITH CHECK (true);
-- Admin policies handled via service role in API, or add specific policies if using authenticated client
